from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib.pagesizes import letter

import os


# =========================================================
# Generate PDF Report
# =========================================================
def generate_pdf_report(report):

    pdf_filename = f"report_{report.id}.pdf"

    pdf_path = os.path.join(
        "reports",
        pdf_filename
    )

    # Create PDF
    doc = SimpleDocTemplate(

        pdf_path,

        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # =====================================================
    # Title
    # =====================================================
    title = Paragraph(

        "AI Assisted Keratoconus Detection Report",

        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # =====================================================
    # Patient Details
    # =====================================================
    patient_info = f"""

    <b>Patient ID:</b> {report.patient_id}<br/>

    <b>Patient Name:</b> {report.patient_name}<br/>

    <b>Age:</b> {report.age}<br/>

    <b>Gender:</b> {report.gender}<br/>

    <b>Eye Type:</b> {report.eye_type}<br/>

    <b>Doctor:</b> {report.doctor_name}<br/>

    <b>Date:</b> {report.created_at}<br/>

    """

    elements.append(

        Paragraph(
            patient_info,
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 20))

    # =====================================================
    # Prediction
    # =====================================================
    prediction_info = f"""

    <b>Prediction:</b> {report.predicted_class}<br/>

    <b>Confidence:</b> {report.confidence}%<br/>

    """

    elements.append(

        Paragraph(
            prediction_info,
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 20))

    # =====================================================
    # Uploaded Image
    # =====================================================
    if os.path.exists(report.uploaded_image):

        elements.append(
            Paragraph(
                "Uploaded Image",
                styles["Heading2"]
            )
        )

        uploaded_img = Image(

            report.uploaded_image,

            width=250,

            height=250
        )

        elements.append(uploaded_img)

        elements.append(Spacer(1, 20))

    # =====================================================
    # GradCAM Image
    # =====================================================
    if os.path.exists(report.gradcam_image):

        elements.append(
            Paragraph(
                "GradCAM Heatmap",
                styles["Heading2"]
            )
        )

        gradcam_img = Image(

            report.gradcam_image,

            width=250,

            height=250
        )

        elements.append(gradcam_img)

        elements.append(Spacer(1, 20))

    # =====================================================
    # Footer
    # =====================================================
    footer = Paragraph(

        "Generated by AI Assisted Keratoconus Detection System",

        styles["Italic"]
    )

    elements.append(footer)

    # Build PDF
    doc.build(elements)

    return pdf_path